### ISSUE TITLE
bugfix:

### ISSUE THREAD

**Issue by miili** [pyrocko/grond#25]
free GNSS targets from the all-component requirement.

effort: one flight time to the far East

**Comment by miili** [comment]
Hi there,
the sparse components are implemented in grond (though this was mainly a pyrocko effort).
I couldn't test this in grond yet, I would be glad if someone could give feedback!

Best, Marius

**Comment by janrid** [comment]
I get now the following error:
(newest pyrocko master and grond dev versions)

stu111977@ukifg-c653:/data3/JAN/grond$ grond check config/grond_insar_gnss_testing.gronf ahar2012_1
grond:grond.dataset        - INFO     - Loading events ...
grond:grond.dataset        - INFO     - Loading events from data/events/ahar2012_1/Catalog.out: ahar2012_2, ahar2012_1
grond:grond.dataset        - INFO     - Loading kite InSAR scenes...
grond:grond.problems.rectangular.problem - WARNING  - Decimation factor for rectangular source set to 4. Results may be inaccurate.
grond:grond.core           - INFO     - Problem: insar_gnss_TestRun_newGNSScode_ahar2012_1
grond:grond.core           - INFO     - Number of target families: 1
grond:grond.core           - INFO     - Number of targets (total): 2
grond:grond.core           - INFO     - Number of targets (selected): 2
Traceback (most recent call last):
  File "/home/stu111977/python/src/bin/grond", line 11, in <module>
    load_entry_point('grond==1.1.0', 'console_scripts', 'grond')()
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/apps/grond.py", line 192, in main
    globals()['command_' + d2u(command)](args)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/apps/grond.py", line 694, in command_check
    stations_used_path=options.stations_used_path)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/core.py", line 290, in check
    results = problem.evaluate(x)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/problems/base.py", line 505, in evaluate
    nthreads=self.nthreads)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 3229, in process
    nthreads=nthreads):
  File "/home/stu111977/python/src/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 2754, in process_static
    base_statics, source, target)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 3123, in _post_process_statics
    return starget.post_process(self, source, base_statics)
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/targets/gnss_campaign/target.py", line 187, in post_process
    obs = self.obs_data
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/targets/gnss_campaign/target.py", line 137, in obs_data
    [s.get_displacement_data() for s in self.campaign.stations])
  File "/home/stu111977/python/src/lib/python3.5/site-packages/grond/targets/gnss_campaign/target.py", line 137, in <listcomp>
    [s.get_displacement_data() for s in self.campaign.stations])
  File "/home/stu111977/python/src/lib/python3.5/site-packages/pyrocko/model/gnss.py", line 133, in get_displacement_data
    return num.array([c.shift for c in self.component.values()])
AttributeError: 'GNSSStation' object has no attribute 'component'

**Comment by hsudha** [comment]
Same errors on my side.

**Comment by hsudha** [comment]
I fixed a missing 's' in `pyrocko/model/gnss.py` and adapted some arrays in `grond` in `targets/gnss_campaign/target.py`.  Maybe the fixes could be nicer, but they seem to work.

**Comment by janrid** [comment]
Works fine now until report creation:
see error code ...
```
jridder@jr-u410:~/Data/MasterTh/grond$ grond report rundir/insar_gnss_testing_ahar2012_1.grun/
grond:grond.report         - INFO     - Creating report entry for run "insar_gnss_testing_ahar2012_1"...
grond:grond.dataset        - INFO     - Loading events from data/events/ahar2012_1/Catalog.out: ahar2012_2, ahar2012_1
grond:grond.dataset        - INFO     - Loading kite InSAR scenes...
grond:grond.plot.collection - INFO     - Figure saved: report/ahar2012_1/insar_gnss_testing_ahar2012_1/plots/acceptance/default/acceptance.default.acceptance.d100.png
grond:grond.plot.collection - INFO     - Figure saved: report/ahar2012_1/insar_gnss_testing_ahar2012_1/plots/acceptance/default/acceptance.default.acceptance_img.d100.png
grond:grond.plot.collection - INFO     - Figure saved: report/ahar2012_1/insar_gnss_testing_ahar2012_1/plots/bootstrap/default/bootstrap.default.main.d100.png
/home/jridder/.local/lib/python3.6/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
/home/jridder/.local/lib/python3.6/site-packages/scipy/signal/signaltools.py:1341: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out_full[ind] += zi
/home/jridder/.local/lib/python3.6/site-packages/scipy/signal/signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/jridder/.local/lib/python3.6/site-packages/scipy/signal/signaltools.py:1350: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zf = out_full[ind]
grond:grond.plot.collection - INFO     - Figure saved: report/ahar2012_1/insar_gnss_testing_ahar2012_1/plots/contributions/default/contributions.default.main.d100.png
grond:grond.report         - WARNING  - Failed to create report entry, removing incomplete subdirectory: report/ahar2012_1/insar_gnss_testing_ahar2012_1
Traceback (most recent call last):
  File "/usr/local/bin/grond", line 11, in <module>
    load_entry_point('grond==1.1.0', 'console_scripts', 'grond')()
  File "/usr/local/lib/python3.6/dist-packages/grond/apps/grond.py", line 192, in main
    globals()['command_' + d2u(command)](args)
  File "/usr/local/lib/python3.6/dist-packages/grond/apps/grond.py", line 1217, in command_report
    make_report, *zip(*payload), nprocs=options.nparallel):
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/parimap.py", line 59, in parimap
    yield function(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/grond/apps/grond.py", line 1077, in make_report
    make_archive=False)
  File "/usr/local/lib/python3.6/dist-packages/grond/report/base.py", line 214, in report
    raise e
  File "/usr/local/lib/python3.6/dist-packages/grond/report/base.py", line 186, in report
    plot_config_collection=pcc)
  File "/usr/local/lib/python3.6/dist-packages/grond/plot/main.py", line 65, in make_plots
    plot.make(env)
  File "/usr/local/lib/python3.6/dist-packages/grond/targets/gnss_campaign/plot.py", line 68, in make
    ''')
  File "/usr/local/lib/python3.6/dist-packages/grond/plot/collection.py", line 181, in create_group_automap
    for item, automap in iter_item_figure:
  File "/usr/local/lib/python3.6/dist-packages/grond/targets/gnss_campaign/plot.py", line 227, in draw_gnss_fits
    yield plot_gnss(gnss_target, result, ifig, vertical)
  File "/usr/local/lib/python3.6/dist-packages/grond/targets/gnss_campaign/plot.py", line 130, in plot_gnss
    sta.up.shift = -result.statics_syn['displacement.d'][ista]
AttributeError: 'NoneType' object has no attribute 'shift'
```

**Comment by hsudha** [comment]
Report for no gnss up components fixed as well. 
Omits now non-existing up-components. Plots for vertical displacement have no stations.

Need to test if a mixture of with and without up-components works. 
Still not working will observations with a single E or a single up component or such.
